spring:
  profiles:
    active: dev
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: mail_fanguangrui@163.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: ...
    # 端口号465或者994
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  # DataSource Config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhoat:3306/fgrapp?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ...
      password: ...
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: localhsot
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ...
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射。
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/*.xml

# 日志配置
logging:
  level:
    com.fgrapp: debug
    org.springframework: warn

aj:
  captcha:
    # 缓存local/redis...
    cache-type: redis
    # 滑动验证，底图路径，不配置将使用默认图片
    #点击验证，底图路径，不配置将使用默认图片
    #    pic-click: classpath:/captchaImage
    # 右下角水印文字
    water-mark: FGRAPP
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 0
    # 历史数据清除开关
    history-data-clear-enable: true
    jigsaw: classpath:/captchaImage/jigsaw
    # 验证码类型default两种都实例化。
    type: blockpuzzle
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: false
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 360
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 60
    # verify接口一分钟内请求数限制
    req-verify-minute-limit: 60

fgr:
  swagger:
    enabled: true
    pathMapping: /
    title: FGRAPP-Admin接口文档
    description: FGRAPP-Admin接口文档-简介
    termsOfServiceUrl: http://${fgr.ip}:${server.port}
    name: fanguangrui
    url: ${fgr.swagger.termsOfServiceUrl}
    email: 898365387@qq.com
    license: MIT
    licenseUrl: www.fgrapp.com
    version: 1.0-SNAPSHOT
  # 名称
  name: FGRAPP
  # ip
  ip: server.fgrapp.com
  # GitHub
  gtihub: https://github.com/maoHuanZhe/fgrapp-admin
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/fgr/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/fgr/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # goFastUrl
  goFastUrl: http://localhost:8003/bill/
  #captchTtype
  captchTtype: math
  # 非对称加密私钥
  privateKey: ...
  #阿里云配置
  ali:
    accessKeyId: ...
    accessKeySecret: ...
    endpoint: dysmsapi.aliyuncs.com
    message:
      signName: FGRAPP
      templateCode: ...
  wechat:
    appId: ...
    appSecret: ...
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Admin-Token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  token-prefix: Bearer
  # 写入Cookie时显式指定的作用域, 用于单点登录二级域名共享Cookie
  cookie-domain: fgrapp.com

